### PR TITLE
Style and language edits

### PR DESCRIPTION
**Pull request by shiffman**
I shorted the "drag and drop" language and adjusted the button style a bit (the grey background made the text hard to see?) @yining1023 or @matamalaortiz obviously go ahead and re-style, I can't believe I just edited some CSS!

new look:

screen shot 2018-06-07 at 4 37 36 pm

### CODE REVIEW

**Comment by yining1023** [comment]
All good! 
@matamalaortiz, any design suggestions?

**Comment by yining1023** [comment]
Sorry I didn't notice it before.
I changed the border of the button to purple. I'm open to other designs too.
screen shot 2018-06-07 at 5 14 05 pm

**Comment by matamalaortiz** [comment]
I think green looks better and keep more consistency with the other button. How do you feel about this (image attached)? 
screen shot 2018-06-07 at 6 13 51 pm

Also, I think I preferred when it has more than 1 label as a result. Although it is clear at the examples inside that there are more predictions.

**Comment by shiffman** [comment]
@matamalaortiz yes, the button design you propose looks great! I agree, I added back in the more "verbose" caption and the curvy up arrow. I will merge this and you can make the design adjustments from there? Or feel free to comment with the CSS for your image above if that's easier.

**Pull request merged**
